CREATE IF NOT EXIST TABLE movie (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) null,
	description TEXT null,
	rating DOUBLE null,
	image VARCHAR(255) null,
	created_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;